#!/bin/bash

# TalkCody Unified Release Script
# Supports Linux, Windows and macOS platforms
# Usage: PLATFORM=linux|windows|macos ARCH=x86_64|aarch64 ./.github/scripts/release.sh

set -e  # Exit on error

echo "========================================="
echo "TalkCody Release Process"
echo "========================================="
echo ""

# Color definitions
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

# Get platform and architecture
PLATFORM=${PLATFORM:-linux}
ARCH=${ARCH:-x86_64}

echo -e "${BLUE}Platform: ${PLATFORM}${NC}"
echo -e "${BLUE}Architecture: ${ARCH}${NC}"
echo ""

# Validate platform
if [ "$PLATFORM" != "linux" ] && [ "$PLATFORM" != "windows" ] && [ "$PLATFORM" != "macos" ]; then
    echo -e "${RED}❌ Error: Unsupported platform: $PLATFORM${NC}"
    echo "   Supported platforms: linux, windows, macos"
    exit 1
fi

# Set platform-specific variables
case "$PLATFORM" in
    linux)
        BUNDLE_DIR="src-tauri/target/release/bundle/appimage"
        ARTIFACT_PATTERN="*.AppImage"
        ARTIFACT_EXT="AppImage"
        PLATFORM_ID="linux-${ARCH}"
        UPDATER_PREFIX="talkcody"
        ;;
    windows)
        BUNDLE_DIR="src-tauri/target/release/bundle/msi"
        ARTIFACT_PATTERN="*.msi"
        ARTIFACT_EXT="msi"
        if [ "$ARCH" = "x86_64" ]; then
            PLATFORM_ID="windows-x86_64"
            WIN_ARCH="x64"
        elif [ "$ARCH" = "aarch64" ]; then
            PLATFORM_ID="windows-aarch64"
            WIN_ARCH="aarch64"
        else
            echo -e "${RED}❌ Error: Unsupported Windows architecture: $ARCH${NC}"
            exit 1
        fi
        UPDATER_PREFIX="talkcody"
        ;;
    macos)
        BUNDLE_DIR="src-tauri/target/release/bundle/macos"
        DMG_DIR="src-tauri/target/release/bundle/dmg"
        ARTIFACT_PATTERN="*.app.tar.gz"
        ARTIFACT_EXT="app.tar.gz"
        if [ "$ARCH" = "x86_64" ]; then
            PLATFORM_ID="darwin-x86_64"
            DMG_PATTERN="*_x64.dmg"
        elif [ "$ARCH" = "aarch64" ]; then
            PLATFORM_ID="darwin-aarch64"
            DMG_PATTERN="*_aarch64.dmg"
        else
            echo -e "${RED}❌ Error: Unsupported macOS architecture: $ARCH${NC}"
            exit 1
        fi
        UPDATER_PREFIX="talkcody"
        ;;
esac

# Check required tools
echo "📋 Checking required tools..."

if ! command -v jq &> /dev/null; then
    echo -e "${RED}❌ Error: jq not installed${NC}"
    exit 1
fi

if ! command -v wrangler &> /dev/null; then
    echo -e "${RED}❌ Error: wrangler not installed${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} All required tools are installed"
echo ""

# Note about TAURI_SIGNING_PRIVATE_KEY
echo -e "${BLUE}ℹ️  Note: This script expects updater artifacts generated by 'bun run tauri build'${NC}"
echo -e "${BLUE}   with TAURI_SIGNING_PRIVATE_KEY environment variable set during build.${NC}"
echo ""

# Get version from environment or tauri.conf.json
if [ -n "$VERSION" ]; then
    echo "📖 Using version from environment: v${VERSION}"
else
    echo "📖 Reading version from tauri.conf.json..."
    VERSION=$(jq -r '.version' src-tauri/tauri.conf.json)
fi

if [ -z "$VERSION" ] || [ "$VERSION" == "null" ]; then
    echo -e "${RED}❌ Error: Cannot read version${NC}"
    exit 1
fi

echo -e "${GREEN}✓${NC} Version: ${BLUE}v${VERSION}${NC}"
echo ""

# Step 1: Find build artifacts
echo "🔍 Step 1/5: Finding build artifacts..."

ARTIFACT_FILE=$(find "$BUNDLE_DIR" -name "$ARTIFACT_PATTERN" 2>/dev/null | head -n 1)

if [ -z "$ARTIFACT_FILE" ]; then
    echo -e "${RED}❌ Error: Build artifact not found in $BUNDLE_DIR${NC}"
    echo "  Expected pattern: $ARTIFACT_PATTERN"
    echo "  Please ensure 'bun run tauri build' was run successfully"
    exit 1
fi

ARTIFACT_FILENAME=$(basename "$ARTIFACT_FILE")

# For macOS, rename .app.tar.gz to include architecture and find DMG file
if [ "$PLATFORM" = "macos" ]; then
    # Rename .app.tar.gz to include architecture (e.g., TalkCody_x86_64.app.tar.gz)
    RENAMED_ARTIFACT="TalkCody_${ARCH}.app.tar.gz"
    RENAMED_ARTIFACT_PATH="$(dirname "$ARTIFACT_FILE")/$RENAMED_ARTIFACT"
    
    echo "  Renaming artifact to include architecture..."
    cp "$ARTIFACT_FILE" "$RENAMED_ARTIFACT_PATH"
    ARTIFACT_FILE="$RENAMED_ARTIFACT_PATH"
    ARTIFACT_FILENAME="$RENAMED_ARTIFACT"
    echo -e "${GREEN}✓${NC} Renamed to: $ARTIFACT_FILENAME"
    
    # Find DMG file
    echo "  Looking for DMG file..."
    DMG_FILE=$(find "$DMG_DIR" -name "$DMG_PATTERN" 2>/dev/null | head -n 1)
    
    if [ -z "$DMG_FILE" ]; then
        echo -e "${RED}❌ Error: DMG file not found in $DMG_DIR${NC}"
        echo "  Expected pattern: $DMG_PATTERN"
        exit 1
    fi
    
    DMG_FILENAME=$(basename "$DMG_FILE")
    echo -e "${GREEN}✓${NC} Found DMG file: $DMG_FILENAME"
fi

echo -e "${GREEN}✓${NC} Found artifact: $ARTIFACT_FILENAME"
echo ""

# Step 2: Find signature file (generated by Tauri build with createUpdaterArtifacts = true)
echo "📦 Step 2/5: Finding signature file..."

# For macOS, signature file is from the original .app.tar.gz before renaming
if [ "$PLATFORM" = "macos" ]; then
    # Find the original TalkCody.app.tar.gz.sig file
    ORIGINAL_ARTIFACT=$(find "$BUNDLE_DIR" -name "TalkCody.app.tar.gz" 2>/dev/null | head -n 1)
    if [ -n "$ORIGINAL_ARTIFACT" ]; then
        SIGNATURE_FILE="${ORIGINAL_ARTIFACT}.sig"
    else
        SIGNATURE_FILE="${ARTIFACT_FILE}.sig"
    fi
else
    # Tauri 2.x generates: {artifact}.sig when createUpdaterArtifacts = true
    SIGNATURE_FILE="${ARTIFACT_FILE}.sig"
fi

if [ ! -f "$SIGNATURE_FILE" ]; then
    echo -e "${RED}❌ Error: Signature file not found: $(basename "$SIGNATURE_FILE")${NC}"
    echo "  Make sure 'createUpdaterArtifacts' is set to true in tauri.conf.json"
    echo "  and TAURI_SIGNING_PRIVATE_KEY environment variable is set during build"
    exit 1
fi

echo -e "${GREEN}✓${NC} Found signature file: $(basename "$SIGNATURE_FILE")"
echo ""

# Step 3: Generate platform-specific manifest fragment
echo "📝 Step 3/5: Generating platform manifest fragment..."

# Read signature content
SIGNATURE=$(cat "$SIGNATURE_FILE")

# Get current date (ISO 8601 format)
PUB_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# CDN URL prefix
CDN_BASE="https://cdn.talkcody.com"

# Configure wrangler authentication
if [ -n "$CLOUDFLARE_API_TOKEN" ]; then
    export CLOUDFLARE_API_TOKEN="$CLOUDFLARE_API_TOKEN"
fi
if [ -n "$CLOUDFLARE_ACCOUNT_ID" ]; then
    export CLOUDFLARE_ACCOUNT_ID="$CLOUDFLARE_ACCOUNT_ID"
fi

# Generate download URLs based on platform
# For macOS: url points to .app.tar.gz (for auto-update), download_url points to .dmg (for manual download)
# For other platforms: both point to the same file
if [ "$PLATFORM" = "macos" ]; then
    UPDATER_URL="${CDN_BASE}/releases/v${VERSION}/$ARTIFACT_FILENAME"
    DOWNLOAD_URL="${CDN_BASE}/releases/v${VERSION}/$DMG_FILENAME"
else
    DOWNLOAD_URL="${CDN_BASE}/releases/v${VERSION}/$ARTIFACT_FILENAME"
    UPDATER_URL="$DOWNLOAD_URL"
fi

# Generate platform-specific manifest fragment
# This will be merged by finalize-release.sh
PLATFORM_MANIFEST_FILE="/tmp/platform-manifest-${PLATFORM}-${ARCH}-$$.json"
PLATFORM_MANIFEST_JSON=$(cat <<EOF
{
  "platform_id": "${PLATFORM_ID}",
  "version": "${VERSION}",
  "pub_date": "${PUB_DATE}",
  "url": "${UPDATER_URL}",
  "signature": "${SIGNATURE}",
  "download_url": "${DOWNLOAD_URL}"
}
EOF
)

echo "$PLATFORM_MANIFEST_JSON" > "$PLATFORM_MANIFEST_FILE"

echo -e "${GREEN}✓${NC} Platform manifest fragment created (${PLATFORM} ${ARCH})"
echo ""

# Step 4: Skip latest.json generation (will be handled by finalize-release job)
echo "📝 Step 4/5: Skipping latest.json generation (handled by finalize job)"
echo ""

# Step 5: Upload to R2
echo "📤 Step 5/5: Uploading files to R2..."

R2_BUCKET="talkcody"
VERSION_PATH="releases/v${VERSION}"

# Helper function to upload with retry
upload_with_retry() {
    local file="$1"
    local remote_path="$2"
    local content_type="$3"
    local max_retries=3
    local retry_count=0

    while [ $retry_count -lt $max_retries ]; do
        if wrangler r2 object put "${remote_path}" \
            --file "$file" \
            --content-type "$content_type" \
            --remote 2>&1; then
            return 0
        fi

        retry_count=$((retry_count + 1))
        if [ $retry_count -lt $max_retries ]; then
            echo -e "${YELLOW}  Upload failed, retrying in 5s (${retry_count}/${max_retries})...${NC}"
            sleep 5
        fi
    done

    echo -e "${RED}  Upload failed after ${max_retries} retries${NC}"
    return 1
}

echo "  Uploading ${PLATFORM} ${ARCH} artifact..."
if ! upload_with_retry "$ARTIFACT_FILE" "${R2_BUCKET}/${VERSION_PATH}/$ARTIFACT_FILENAME" "application/octet-stream"; then
    exit 1
fi

echo "  Uploading ${PLATFORM} ${ARCH} signature file..."
if ! upload_with_retry "$SIGNATURE_FILE" "${R2_BUCKET}/${VERSION_PATH}/$(basename "$SIGNATURE_FILE")" "text/plain"; then
    exit 1
fi

# For macOS, also upload the DMG file
if [ "$PLATFORM" = "macos" ]; then
    echo "  Uploading ${PLATFORM} ${ARCH} DMG file..."
    if ! upload_with_retry "$DMG_FILE" "${R2_BUCKET}/${VERSION_PATH}/$DMG_FILENAME" "application/x-apple-diskimage"; then
        exit 1
    fi
fi

echo "  Uploading platform manifest fragment..."
PLATFORM_MANIFEST_FILENAME="platform-manifest-${PLATFORM}-${ARCH}.json"
if ! upload_with_retry "$PLATFORM_MANIFEST_FILE" "${R2_BUCKET}/${VERSION_PATH}/${PLATFORM_MANIFEST_FILENAME}" "application/json"; then
    exit 1
fi

echo -e "${BLUE}  Note: Final manifest.json and latest.json will be generated by finalize-release job${NC}"

echo -e "${GREEN}✓${NC} ${PLATFORM} ${ARCH} files uploaded"
echo ""

# Clean up temporary files
rm -f "$PLATFORM_MANIFEST_FILE"

# Done
echo "========================================="
echo -e "${GREEN}🎉 ${PLATFORM} Release Complete!${NC}"
echo "========================================="
echo ""
echo "📦 Release Info:"
echo "  Version: ${BLUE}v${VERSION}${NC}"
echo "  Platform: ${PLATFORM} ${ARCH}"
echo "  Artifact: ${ARTIFACT_FILENAME}"
echo ""
echo "🌐 Download Links:"
echo "  ${BLUE}${CDN_BASE}/releases/v${VERSION}/${ARTIFACT_FILENAME}${NC}"
echo ""
echo "🔄 Update API:"
echo "  ${BLUE}https://api.talkcody.com/api/updates/${PLATFORM}/${ARCH}/${VERSION}${NC}"
echo ""
