use crate::llm::types::{AuthType, ProtocolType, ProviderConfig};

pub fn builtin_providers() -> Vec<ProviderConfig> {
    vec![
        ProviderConfig {
            id: "talkcody".to_string(),
            name: "TalkCody Free".to_string(),
            protocol: ProtocolType::Claude,
            base_url: "https://api.talkcody.com/api/talkcody/v1".to_string(),
            api_key_name: "TALKCODY_ENABLED".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::TalkCodyJwt,
        },
        ProviderConfig {
            id: "openai".to_string(),
            name: "OpenAI".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.openai.com/v1".to_string(),
            api_key_name: "OPENAI_API_KEY".to_string(),
            supports_oauth: true,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "github_copilot".to_string(),
            name: "GitHub Copilot".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.githubcopilot.com".to_string(),
            api_key_name: "GITHUB_COPILOT_TOKEN".to_string(),
            supports_oauth: true,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: Some(
                [
                    (
                        "User-Agent".to_string(),
                        "GitHubCopilotChat/0.35.0".to_string(),
                    ),
                    ("Editor-Version".to_string(), "vscode/1.105.1".to_string()),
                    (
                        "Editor-Plugin-Version".to_string(),
                        "copilot-chat/0.35.0".to_string(),
                    ),
                    (
                        "Copilot-Integration-Id".to_string(),
                        "vscode-chat".to_string(),
                    ),
                ]
                .into_iter()
                .collect(),
            ),
            extra_body: None,
            auth_type: AuthType::OAuthBearer,
        },
        ProviderConfig {
            id: "openRouter".to_string(),
            name: "OpenRouter".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://openrouter.ai/api/v1".to_string(),
            api_key_name: "OPEN_ROUTER_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: Some(
                [
                    (
                        "HTTP-Referer".to_string(),
                        "https://talkcody.com".to_string(),
                    ),
                    ("X-Title".to_string(), "TalkCody".to_string()),
                ]
                .into_iter()
                .collect(),
            ),
            extra_body: Some(serde_json::json!({
                "reasoning": { "enabled": true }
            })),
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "aiGateway".to_string(),
            name: "Vercel AI Gateway".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://ai-gateway.vercel.sh/v1".to_string(),
            api_key_name: "AI_GATEWAY_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: Some(
                [
                    (
                        "http-referer".to_string(),
                        "https://talkcody.com".to_string(),
                    ),
                    ("x-title".to_string(), "TalkCody".to_string()),
                ]
                .into_iter()
                .collect(),
            ),
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "deepseek".to_string(),
            name: "Deepseek".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.deepseek.com/v1".to_string(),
            api_key_name: "DEEPSEEK_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "zhipu".to_string(),
            name: "Zhipu AI".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://open.bigmodel.cn/api/paas/v4".to_string(),
            api_key_name: "ZHIPU_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: true,
            supports_international: false,
            coding_plan_base_url: Some("https://open.bigmodel.cn/api/coding/paas/v4".to_string()),
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "zai".to_string(),
            name: "Z.AI".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.z.ai/api/paas/v4".to_string(),
            api_key_name: "ZAI_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: true,
            supports_international: false,
            coding_plan_base_url: Some("https://api.z.ai/api/coding/paas/v4".to_string()),
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "MiniMax".to_string(),
            name: "MiniMax".to_string(),
            protocol: ProtocolType::Claude,
            base_url: "https://api.minimaxi.com/anthropic/v1".to_string(),
            api_key_name: "MINIMAX_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: true,
            supports_international: true,
            coding_plan_base_url: None,
            international_base_url: Some("https://api.minimaxi.chat/anthropic/v1".to_string()),
            headers: None,
            extra_body: None,
            auth_type: AuthType::ApiKey,
        },
        ProviderConfig {
            id: "moonshot".to_string(),
            name: "Moonshot".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.moonshot.cn/v1".to_string(),
            api_key_name: "MOONSHOT_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: true,
            coding_plan_base_url: None,
            international_base_url: Some("https://api.kimi.com/v1".to_string()),
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "kimi_coding".to_string(),
            name: "Kimi Coding Plan".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.kimi.com/coding/v1".to_string(),
            api_key_name: "KIMI_CODING_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "zenmux".to_string(),
            name: "ZenMux".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://zenmux.ai/api/v1".to_string(),
            api_key_name: "ZENMUX_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "groq".to_string(),
            name: "Groq".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.groq.com/openai/v1".to_string(),
            api_key_name: "GROQ_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "ollama".to_string(),
            name: "Ollama".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "http://127.0.0.1:11434/v1".to_string(),
            api_key_name: "OLLAMA_ENABLED".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::None,
        },
        ProviderConfig {
            id: "lmstudio".to_string(),
            name: "LM Studio".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "http://127.0.0.1:1234/v1".to_string(),
            api_key_name: "LMSTUDIO_ENABLED".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::None,
        },
        ProviderConfig {
            id: "anthropic".to_string(),
            name: "Anthropic".to_string(),
            protocol: ProtocolType::Claude,
            base_url: "https://api.anthropic.com/v1".to_string(),
            api_key_name: "ANTHROPIC_API_KEY".to_string(),
            supports_oauth: true,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::OAuthBearer,
        },
        ProviderConfig {
            id: "google".to_string(),
            name: "Google AI".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://generativelanguage.googleapis.com/v1beta".to_string(),
            api_key_name: "GOOGLE_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "volcengine".to_string(),
            name: "Volcengine (ByteDance)".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://ark.cn-beijing.volces.com/api/v3".to_string(),
            api_key_name: "VOLCENGINE_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "alibaba".to_string(),
            name: "Alibaba (DashScope)".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://dashscope.aliyuncs.com/compatible-mode/v1".to_string(),
            api_key_name: "ALIBABA_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: true,
            supports_international: false,
            coding_plan_base_url: Some("https://coding.dashscope.aliyuncs.com/v1".to_string()),
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "tavily".to_string(),
            name: "Tavily Web Search".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.tavily.com".to_string(),
            api_key_name: "TAVILY_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "serper".to_string(),
            name: "Serper Web Search".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://google.serper.dev".to_string(),
            api_key_name: "SERPER_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
        ProviderConfig {
            id: "elevenlabs".to_string(),
            name: "Eleven Labs Text-to-Speech".to_string(),
            protocol: ProtocolType::OpenAiCompatible,
            base_url: "https://api.elevenlabs.io".to_string(),
            api_key_name: "ELEVENLABS_API_KEY".to_string(),
            supports_oauth: false,
            supports_coding_plan: false,
            supports_international: false,
            coding_plan_base_url: None,
            international_base_url: None,
            headers: None,
            extra_body: None,
            auth_type: AuthType::Bearer,
        },
    ]
}
